paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Get all products from the DB
      responses:
        '200':
          description: Products fetched successfully from the DB
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '401':
          description: Debes iniciar sesión primero
        '500':
          description: Internal Server Error
    post:
      tags:
        - Products
      summary: Create new product 
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#components/schemas/Product'
      responses:
        '200':
          description: New product created!
        '401':
          description: Debes iniciar sesión primero        
        '500':
          description: Internal Server Error



  /api/products/realtimeproducts:
    get:
      tags:
        - Products    
      summary: Get all products from the DB with socket.io
      responses:
        '200':
          description: Products fetched successfully from the DB
          content: 
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '500':
          description: Internal Server Error
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Get a single product by their id
      parameters: 
        - name: pid
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: String
      responses:
        '200':
          description: Product from DB with the given prodId
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'

    put:
      tags:
        - Products
      summary: Updates a single product for a given prodId
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'

    delete:
      tags:
        - Products
      summary: Delete a single product for a given prodId
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to fetch
          schema:
            $type: String



components:
  schemas:
    Product: 
      type: Object
      properties:
        _id:
          type: ObjectId
          description: Autogenerated MongoDB ID
        title:
          type: String
          description: Product title
        description:
          type: String
          description: Product description
        price:
          type: Number
          description: Product price
        thumbnail:
          type: Array
          description: Product image
        code:
          type: String
          description: Product reference code
        stock:
          type: Number
          description: available stock
        status:
          type: Boolean
          description: Product status
        category:
          type: String
          description: Product category
        owner:
          type: String
          description: Product owner
      example:
        title: Remera Bordada Camboya
        description: Cuello en V - manga corta - tela algodón
        price: 3690
        thumbnail: []
        code: aiNiIPXE9HZEzCpgA597
        stock: 26
        status: true
        category: remera
  requestBodies:
    updateProduct:
      type: Object
      properties:
        title:
          type: String
          description: Product title
        description:
          type: String
          description: Product description
        price:
          type: Number
          description: Product price
        thumbnail:
          type: Array
          description: Product image
        code:
          type: String
          description: Product reference code
        stock:
          type: Number
          description: available stock
        status:
          type: Boolean
          description: Product status
        category:
          type: String
          description: Product category
        owner:
          type: String
          description: Product owner
      example:
        title: test swagger product
        description: for testing only
        price: 4200
        thumbnail: []
        code: aiNiIPXE9HZEzCpgA597
        stock: 20
        status: true
        category: remera
